server.port: 9090
logging.config: classpath:logback-test.xml
# 测试环境配置  
# 测试环境：java -jar XXX.jar --spring.profiles.active=test 
spring:  
  profiles: test
spring.datasource:
  url: "jdbc:mysql://localhost:3306/ermdev2?useUnicode=true&characterEncoding=UTF-8"
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: root