server.port: 9092
logging.config: classpath:logback-prod.xml
# 生产环境配置  
# 生产环境：java -jar XXX.jar --spring.profiles.active=prod 
spring:  
  profiles: prod
spring.datasource:
    url: jdbc:mysql://localhost:3306/erm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

